name: Windows CI
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Setup VS
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: 2019
 
    - name: Setup Perl
      uses: rtomayko/perl-action@v1.1.2
 
    - name: Configure OpenSSL
      run: |
        cd \openssl
        perl Configure VC-WIN32 no-shared --prefix=C:\msys64\home\runner\openssl-latest --openssldir=C:\msys64\home\runner\openssl-latest
        nmake
        nmake test
        nmake install
      env:
        PATH: ${{ github.workspace }}\msys64\usr\bin;${{ github.workspace }}\msys64\mingw64\bin;$PATH
