name: Build OpenSSL for Windows

on: [push]

jobs:
  build-openssl:
    runs-on: windows-latest

    steps:
    - name: Install Perl
      shell: pwsh
      run: |
        $url = "https://www.activestate.com/products/perl/download/?version=5.30.1.1&platform=win64"
        Invoke-WebRequest -Uri $url -OutFile perl-installer.exe
        Start-Process .\perl-installer.exe -Wait -ArgumentList "/S /D=C:\Perl64"

    - name: Install NASM
      shell: pwsh
      run: |
        $url = "https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-installer-x64.exe"
        Invoke-WebRequest -Uri $url -OutFile nasm-installer.exe
        Start-Process .\nasm-installer.exe -Wait -ArgumentList "/S"

    - name: Add to PATH
      shell: pwsh
      run: |
        $env:Path += ";C:\Perl64\bin"
        $env:Path += ";C:\Program Files\NASM"

    - name: Fetch openssl code
      run: |
        git clone https://github.com/openssl/openssl.git
        cd openssl
        git checkout openssl-$OPENSSL_VERSION

    - name: Configure OpenSSL
      working-directory: ./openssl
      run: perl Configure VC-WIN64A --prefix=D:\OpenSSL

    - name: Build OpenSSL
      working-directory: ./openssl
      run: nmake

    - name: Install OpenSSL
      working-directory: ./openssl
      run: nmake install
